kind: pipeline
name: default

steps:
- name: tests
  image: golang
  environment:
    fusio_test_db_type: postgres
    fusio_test_db_port: 
      from_secret: 
        fusio_test_db_port
    fusio_test_db_host:
      from_secret:
        fusio_test_db_host
    fusio_test_db_database:
      from_secret:
        fusio_test_db_database
    fusio_test_db_user:
      from_secret:
        fusio_test_db_user
    fusio_test_db_password:
      from_secret:
        fusio_test_db_password
    fusio_test_redis_url:
        cache:6379
  commands:
  - go mod download
  - go build
  - go test ./...

- name: notify
  image: plugins/matrix
  settings:
    homeserver:
      from_secret: matrix_server
    roomid: 
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username
    password:
      from_secret: matrix_password
  when:
    status:
    - failure


services:
- name: cache
  image: redis
